// packages/e2e-svelte/src/App.svelte
<script lang="ts">
  // Svelte components *can* be consumed in source form (as Morpho currenlty
  // provides), but it is not recommended:
  // https://github.com/sveltejs/component-template/issues/29#issuecomment-905481560

  //@ts-ignore
  import MyComponent from '@builder.io/e2e-app/svelte/components/my-component.svelte';
</script>

<MyComponent></MyComponent>

// packages/e2e-solid/src/App.tsx
// Morpho output for not yet include .d.ts, so ignore the types when importing.
// @ts-ignore
import MyComponent from '@builder.io/e2e-app/solid/components/my-component.lite.jsx';

import type { Component } from 'solid-js';

const App: Component = () => {
  return <MyComponent></MyComponent>;
};

export default App;
